#!/bin/bash

source script/setup-env $@

# set the working directory to the root of the project
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

if [[ "$CI" == "true" ]]; then
  source script/ci-env
fi

crystal run spec/acceptance/acceptance.cr
