#!/bin/bash

set -e

source script/setup-env $@

if [[ "$CI" == "true" ]]; then
  source script/ci-env
fi

# if the --production flag is passed or the CRYSTAL_ENV environment variable is set to production,
# always ensure the CRYSTAL_PATH is set with vendored shards
if [[ "$@" == *"--production"* ]] || [[ "$CRYSTAL_ENV" == "production" ]]; then
  echo "🔨 setting CRYSTAL_PATH to $VENDOR_DIR/shards/install:$(crystal env CRYSTAL_PATH)"
  export CRYSTAL_PATH="vendor/shards/install:$(crystal env CRYSTAL_PATH)"
fi

echo -e "🔨 ${BLUE}building in ${PURPLE}release${BLUE} mode${OFF}"
shards build --production --release --progress --debug --error-trace
echo -e "📦 ${GREEN}build complete${OFF}"
