#!/bin/bash

set -e

# COLORS
OFF='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'

# set the working directory to the root of the project
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

echo -e "🖌️  ${BLUE}linting ${PURPLE}crystal${BLUE} files..."

"$DIR/bin/ameba" $@

echo -e "✅ ${GREEN}linting complete!${OFF}"
