#!/bin/bash

set -e

# COLORS
OFF='\033[0m'
RED='\033[0;31m'
GREEN='\033[0;32m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'

# set the working directory to the root of the project
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && cd .. && pwd )"

echo -e "📦 ${BLUE}Running ${PURPLE}shards update${BLUE} to update all dependencies${OFF}"

script/preinstall

SHARDS_CACHE_PATH="$DIR/.cache/shards" shards update --skip-postinstall --skip-executables $@

script/postinstall

echo -e "✅ ${GREEN}All dependencies have been updated!${OFF}"
